title: ASHAAB RIZVI
logo: https://ashaabrizvi.github.io/images/logo.png # your photo (or logo) here
description: Data Geek
  
social:
  - title: email
    url: mailto:ashaabrizvi11@gmail.com
  - title: github
    url: https://github.com/ashaabrizvi
  - title: linkedin
    url: https://www.linkedin.com/in/ashaabrizvi
theme: jekyll-theme-minimal
